version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mathdb
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5555:5432

  migrations:
    build:
      context: .
      dockerfile: servers.dockerfile
      target: migrations
    restart: on-failure
    depends_on:
      - db

  http-server:
    build:
      context: .
      dockerfile: servers.dockerfile
      target: http-server
    ports:
      - 9000:9000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=mathdb
    depends_on:
      - migrations

  socket-server:
    build:
      context: .
      dockerfile: servers.dockerfile
      target: socket-server
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=mathdb
    depends_on:
      - migrations

  unit_tests:
    build:
      context: .
      dockerfile: tests.dockerfile
      target: unit-tests