version: "3"

services:
  test-db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mathdb
    ports:
      - 5555:5432

  migrations:
    build:
      context: .
      dockerfile: servers.dockerfile
      target: migrations
    restart: on-failure
    environment:
      - DB_HOST=test-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=mathdb
    depends_on:
      - test-db

  socket-server:
    build:
      context: .
      dockerfile: servers.dockerfile
      target: socket-server
    ports:
      - 8000:8000
    environment:
      - SOCKET_PORT=8000
      - DB_HOST=test-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=mathdb
    depends_on:
      - migrations

  integration-tests-socket:
    build:
      context: .
      dockerfile: tests.dockerfile
      target: integration-tests-socket
    environment:
      - SOCKET_HOST=socket-server
      - SOCKET_PORT=8000
    restart: on-failure
    depends_on:
      - migrations