version: "3"

services:
  db:
    image: mongo:latest
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    ports:
      - 9999:9999
    depends_on:
      - db

  unit-tests:
    build:
      context: .
      dockerfile: tests.dockerfile
      target: unit-tests
